### ISSUE TITLE
M49 (unstats-geographical-regions.json) data

### ISSUE THREAD

**Issue by mcarans** [openclimatedata/countrygroups#2]
Just wondering for the M49 data from where you get the JSON file? Are you scraping the unstats website and generating the json or making it manually or do you have access to an updated file or feed?

Also wondering what is your update policy?

**Comment by rgieseke** [comment]
For the unstats regions the source is a manually created file:

https://github.com/openclimatedata/countrygroups/tree/master/archive

YAML, because it seemed the easiest to edit. The JSON is then just converted from the yaml file including some renaming to stay in line with naming conventions of the other datasets:

https://github.com/openclimatedata/countrygroups/blob/master/scripts/unstats-geographical-regions.py

Always happy about updates. New groups as well, if they appear to have broader applicability.

**Comment by rgieseke** [comment]
Got the wrong number in the commit, but I guess this is still solved! Thanks for the feedback!

**Comment by mcarans** [comment]
Thanks. Since asking about this, I have made a library: https://pypi.python.org/pypi/hdx-python-country/ that reads UNStats M49 data directly from their website.

**Comment by rgieseke** [comment]
Nice work, thanks for letting me know!
